trigger:
- main

pool:
  name: Default
  # vmImage: ubuntu-latest

resources:
- repo: self

variables:
  imageName: 'foloo12/backend:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
    - job: Build
      displayName: Build-Push image
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker registry connection'
            repository: 'foloo12/backend'
            command: 'buildAndPush'
            Dockerfile: '**/Backend/dockerfile'
            buildContext: '.'

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    steps:
      - task: CopyFiles@2
        displayName: Copy files
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/*.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
      - task: PublishBuildArtifacts@1
        displayName: Publish manifests
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'manifests'
          publishLocation: 'Container'
          
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'manifests'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: KubernetesManifest@1
        inputs:
          action: 'deploy'
          connectionType: 'azureResourceManager'
          azureSubscriptionConnection: 'TestSubscription(2556f72d-531e-4f12-b57b-892ab4e07d2b)'
          azureResourceGroup: 'kubernetes_dev'
          kubernetesCluster: 'k8stest_dev'
          useClusterAdmin: true
          namespace: 'default'
          manifests: '$(System.ArtifactsDirectory)/Backend/deployment.yaml'
          containers: '$(imageName)'
