version: "3.9"
services:
  flask-app:
    build: 
      context: .
      dockerfile: ./frontend/dockerfile
    image: foloo12/frontend:0.0.7
    container_name: frontendservice
    ports:
      - "3000:5000"
    restart: always
    networks:
      - flask-app-network

  backend:
    build: 
      context: .
      dockerfile: ./Backend/dockerfile
    image: foloo12/backend:0.0.7
    container_name: backendservice
    ports:
      - "3001:5001"
    restart: always
    networks:
      - flask-app-network

networks:
  flask-app-network: