trigger:
- main

resources:
- repo: self

pool:
  name: Default
variables:
  imageName: 'foloo12/frontend:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker registry connection'
        repository: 'foloo12/frontend'
        command: 'buildAndPush'
        Dockerfile: '**/frontend/dockerfile'
        buildContext: '.'
- stage: Deploy
  displayName: Deploy image
  jobs:
    - job: Deploy
      displayName: Deploy Job
      steps:
        - task: CopyFiles@2
          displayName: Copy kubernetes manifests
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            Contents: '**/*.yaml'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        
        - task: PublishBuildArtifacts@1
          displayName: Publish manifests
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'manifests'
            publishLocation: 'Container'
        
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'manifests'
            downloadPath: '$(System.ArtifactsDirectory)'
        
        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'K8s cluster connection'
            namespace: 'default'
            manifests: '$(System.ArtifactsDirectory)/frontend/deployment.yaml'
            containers: '$(imageName)'
