trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      # vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build push image
      inputs:
        containerRegistry: 'Docker registry connection'
        repository: 'foloo12/frontend'
        command: 'buildAndPush'
        Dockerfile: '$(System.DefaultWorkingDirectory)/frontend/dockerfile'
        buildContext: '$(System.DefaultWorkingDirectory)/frontend'
        tags: '$(tag)'
